<?php
$title = 'Horas Trabajadas · Workforce360 AI';
require BASE_PATH . '/app/Views/layouts/header.php';
$formatMinutes = static function (int $minutes): string { $negative=$minutes<0; $minutes=abs($minutes); $h=intdiv($minutes,60); $r=$minutes%60; $value=$h>0?sprintf('%dh %02dm',$h,$r):$r.' min'; return $negative?'-'.$value:$value; };
$selectedCollaborator=''; foreach($collaborators as $item) if((int)($filters['colaborador']??0)===(int)$item['id_colaborador']){$selectedCollaborator=trim($item['nombres'].' '.$item['apellidos']);break;}
$selectedArea=''; foreach($areas as $item) if((int)($filters['area']??0)===(int)$item['id_area']){$selectedArea=(string)$item['nombre'];break;}
$stateLabel=$filters['estado']!==''?$filters['estado']:'Todos';
?>
<div class="page-hero mb-4 no-print"><div class="page-hero-main"><div class="page-hero-icon"><i class="fa-solid fa-business-time"></i></div><div><h1>Reporte de Horas Trabajadas</h1><p>Compara horas programadas, tiempo efectivo y cumplimiento de jornada.</p></div></div><a href="<?= e(route_url('reportes')) ?>" class="btn btn-outline-secondary"><i class="fa-solid fa-arrow-left me-2"></i>Centro de Reportes</a></div>
<div class="card shadow-sm mb-4 no-print"><div class="card-body p-4"><form method="get" action="<?= e(base_url('public/index.php')) ?>" class="row g-3 align-items-end"><input type="hidden" name="route" value="reportes/horas-trabajadas"><div class="col-md-6 col-xl-2"><label class="form-label fw-semibold">Desde</label><input type="date" name="desde" class="form-control" value="<?= e($filters['desde']) ?>"></div><div class="col-md-6 col-xl-2"><label class="form-label fw-semibold">Hasta</label><input type="date" name="hasta" class="form-control" value="<?= e($filters['hasta']) ?>"></div><div class="col-md-6 col-xl-3"><label class="form-label fw-semibold">Colaborador</label><select name="colaborador" class="form-select"><option value="">Todos</option><?php foreach($collaborators as $item): ?><option value="<?= e($item['id_colaborador']) ?>" <?= (int)($filters['colaborador']??0)===(int)$item['id_colaborador']?'selected':'' ?>><?= e($item['codigo_trabajador'].' · '.$item['apellidos'].', '.$item['nombres']) ?></option><?php endforeach; ?></select></div><div class="col-md-6 col-xl-2"><label class="form-label fw-semibold">Área</label><select name="area" class="form-select"><option value="">Todas</option><?php foreach($areas as $item): ?><option value="<?= e($item['id_area']) ?>" <?= (int)($filters['area']??0)===(int)$item['id_area']?'selected':'' ?>><?= e($item['nombre']) ?></option><?php endforeach; ?></select></div><div class="col-md-6 col-xl-2"><label class="form-label fw-semibold">Jornada</label><select name="estado" class="form-select"><option value="">Todas</option><option value="COMPLETA" <?= ($filters['estado']??'')==='COMPLETA'?'selected':'' ?>>Completa</option><option value="PARCIAL" <?= ($filters['estado']??'')==='PARCIAL'?'selected':'' ?>>Parcial</option></select></div><div class="col-md-6 col-xl-1 d-grid"><button class="btn btn-primary" type="submit" title="Aplicar filtros"><i class="fa-solid fa-filter"></i></button></div></form></div></div>
<div class="report-actions no-print"><button type="button" class="btn btn-success" data-report-excel><i class="fa-solid fa-file-excel me-2"></i>Excel</button><button type="button" class="btn btn-danger" data-report-pdf><i class="fa-solid fa-file-pdf me-2"></i>PDF</button><button type="button" class="btn btn-dark" onclick="window.print()"><i class="fa-solid fa-print me-2"></i>Imprimir</button></div>
<section class="report-export-root" data-report-export data-report-title="Reporte de Horas Trabajadas" data-file-name="Reporte_Horas_Trabajadas_<?= e($filters['desde']) ?>_<?= e($filters['hasta']) ?>" data-logo-url="<?= e(asset('devioz-logo1.png')) ?>">
<div class="report-export-meta d-none"><span data-export-meta data-label="Periodo" data-value="<?= e(date('d/m/Y',strtotime($filters['desde'])).' al '.date('d/m/Y',strtotime($filters['hasta']))) ?>"></span><span data-export-meta data-label="Área" data-value="<?= e($selectedArea?:'Todas') ?>"></span><span data-export-meta data-label="Colaborador" data-value="<?= e($selectedCollaborator?:'Todos') ?>"></span><span data-export-meta data-label="Jornada" data-value="<?= e($stateLabel) ?>"></span><span data-export-meta data-label="Generado" data-value="<?= e($generatedAt->format('d/m/Y H:i')) ?>"></span></div>
<section class="print-report-header"><div class="print-brand-row"><img src="<?= e(asset('devioz-logo1.png')) ?>" alt="DEVIOZ" class="print-brand-logo"><div class="print-company">WORKFORCE360 AI</div><div class="print-report-title">REPORTE DE HORAS TRABAJADAS</div></div><div class="print-report-meta"><div><strong>Periodo:</strong> <?= e(date('d/m/Y',strtotime($filters['desde']))) ?> al <?= e(date('d/m/Y',strtotime($filters['hasta']))) ?></div><div><strong>Área:</strong> <?= e($selectedArea?:'Todas') ?></div><div><strong>Colaborador:</strong> <?= e($selectedCollaborator?:'Todos') ?></div><div><strong>Generado:</strong> <?= e($generatedAt->format('d/m/Y H:i')) ?></div></div></section>
<div class="row g-3 mb-4 report-summary-grid summary-five" data-export-summary><div class="col-6 col-xl"><div class="report-summary-card"><span>Jornadas</span><strong><?= e($summary['jornadas']) ?></strong><small>Registros analizados</small></div></div><div class="col-6 col-xl"><div class="report-summary-card"><span>Programadas</span><strong><?= e(number_format($summary['minutos_programados']/60,1)) ?> h</strong><small>Tiempo esperado</small></div></div><div class="col-6 col-xl"><div class="report-summary-card"><span>Trabajadas</span><strong><?= e(number_format($summary['minutos_trabajados']/60,1)) ?> h</strong><small>Tiempo efectivo</small></div></div><div class="col-6 col-xl"><div class="report-summary-card"><span>Diferencia</span><strong><?= e($formatMinutes((int)$summary['diferencia_minutos'])) ?></strong><small>Trabajado - programado</small></div></div><div class="col-6 col-xl"><div class="report-summary-card"><span>Cumplimiento</span><strong><?= e(number_format((float)$summary['cumplimiento'],1)) ?> %</strong><small>Jornada efectiva</small></div></div></div>
<div class="card shadow-sm report-table-card"><div class="card-header py-3 px-4 no-print"><h2 class="h6 fw-bold mb-0"><i class="fa-solid fa-table-list me-2"></i>Detalle de horas y cumplimiento</h2></div><div class="table-responsive"><table class="table app-table report-data-table align-middle mb-0" data-export-table><thead><tr><th>#</th><th>Código</th><th>Colaborador</th><th>Área</th><th>Fecha</th><th>Horario</th><th>Programado</th><th>Trabajado</th><th>Diferencia</th><th>Cumplimiento</th><th>Estado</th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="11" class="text-center py-5 text-secondary">No se encontraron jornadas para los filtros seleccionados.</td></tr><?php else: foreach($rows as $i=>$row): $compliance=(float)$row['cumplimiento_porcentaje']; $compBadge=$compliance>=95?'bg-success-subtle text-success-emphasis':($compliance>=80?'bg-warning-subtle text-warning-emphasis':'bg-danger-subtle text-danger-emphasis'); ?><tr><td><?= e($i+1) ?></td><td><strong><?= e($row['codigo_trabajador']) ?></strong></td><td><div class="fw-semibold"><?= e($row['nombres'].' '.$row['apellidos']) ?></div><div class="small text-secondary"><?= e($row['cargo']?:'Sin cargo') ?></div></td><td><?= e($row['area_nombre']?:'—') ?></td><td><?= e(date('d/m/Y',strtotime($row['fecha']))) ?></td><td><?= e($row['horario_nombre']?:'—') ?></td><td><?= e($formatMinutes((int)$row['minutos_programados'])) ?></td><td><?= e($formatMinutes((int)$row['minutos_trabajados'])) ?></td><td><?= e($formatMinutes((int)$row['diferencia_minutos'])) ?></td><td><span class="badge <?= e($compBadge) ?>"><?= e(number_format($compliance,1)) ?> %</span></td><td><?= e($row['estado']) ?></td></tr><?php endforeach; endif; ?></tbody></table></div></div><div class="print-report-footer">Workforce360 AI · DEVIOZ · Reporte generado automáticamente desde el sistema.</div></section>
<?php require BASE_PATH . '/app/Views/layouts/footer.php'; ?>
