<?php
$title = 'Reporte de Incidencias · Workforce360 AI';
require BASE_PATH . '/app/Views/layouts/header.php';
$selectedCollaborator=''; foreach($collaborators as $item) if((int)($filters['colaborador']??0)===(int)$item['id_colaborador']){$selectedCollaborator=trim($item['nombres'].' '.$item['apellidos']);break;}
$selectedArea=''; foreach($areas as $item) if((int)($filters['area']??0)===(int)$item['id_area']){$selectedArea=(string)$item['nombre'];break;}
$selectedType=''; foreach($incidentTypes as $item) if((int)($filters['tipo']??0)===(int)$item['id_tipo_incidencia']){$selectedType=(string)$item['nombre'];break;}
$stateLabel=$filters['estado']!==''?$filters['estado']:'Todos';
$badgeForState = static function(string $state): string {
    return match($state){
        'APROBADA'=>'bg-success-subtle text-success-emphasis',
        'PENDIENTE'=>'bg-warning-subtle text-warning-emphasis',
        'RECHAZADA'=>'bg-danger-subtle text-danger-emphasis',
        'ANULADA'=>'bg-secondary-subtle text-secondary-emphasis',
        default=>'bg-info-subtle text-info-emphasis',
    };
};
?>
<div class="page-hero mb-4 no-print"><div class="page-hero-main"><div class="page-hero-icon"><i class="fa-solid fa-file-medical"></i></div><div><h1>Reporte de Incidencias</h1><p>Vacaciones, licencias, permisos, descansos médicos y demás situaciones laborales.</p></div></div><a href="<?= e(route_url('reportes')) ?>" class="btn btn-outline-secondary"><i class="fa-solid fa-arrow-left me-2"></i>Centro de Reportes</a></div>
<div class="card shadow-sm mb-4 no-print"><div class="card-body p-4"><form method="get" action="<?= e(base_url('public/index.php')) ?>" class="row g-3 align-items-end"><input type="hidden" name="route" value="reportes/incidencias"><div class="col-md-6 col-xl-2"><label class="form-label fw-semibold">Desde</label><input type="date" name="desde" class="form-control" value="<?= e($filters['desde']) ?>"></div><div class="col-md-6 col-xl-2"><label class="form-label fw-semibold">Hasta</label><input type="date" name="hasta" class="form-control" value="<?= e($filters['hasta']) ?>"></div><div class="col-md-6 col-xl-2"><label class="form-label fw-semibold">Colaborador</label><select name="colaborador" class="form-select"><option value="">Todos</option><?php foreach($collaborators as $item): ?><option value="<?= e($item['id_colaborador']) ?>" <?= (int)($filters['colaborador']??0)===(int)$item['id_colaborador']?'selected':'' ?>><?= e($item['apellidos'].', '.$item['nombres']) ?></option><?php endforeach; ?></select></div><div class="col-md-6 col-xl-2"><label class="form-label fw-semibold">Área</label><select name="area" class="form-select"><option value="">Todas</option><?php foreach($areas as $item): ?><option value="<?= e($item['id_area']) ?>" <?= (int)($filters['area']??0)===(int)$item['id_area']?'selected':'' ?>><?= e($item['nombre']) ?></option><?php endforeach; ?></select></div><div class="col-md-6 col-xl-2"><label class="form-label fw-semibold">Tipo</label><select name="tipo" class="form-select"><option value="">Todos</option><?php foreach($incidentTypes as $item): ?><option value="<?= e($item['id_tipo_incidencia']) ?>" <?= (int)($filters['tipo']??0)===(int)$item['id_tipo_incidencia']?'selected':'' ?>><?= e($item['nombre']) ?></option><?php endforeach; ?></select></div><div class="col-md-6 col-xl-1"><label class="form-label fw-semibold">Estado</label><select name="estado" class="form-select"><option value="">Todos</option><?php foreach(['REGISTRADA','PENDIENTE','APROBADA','RECHAZADA','ANULADA'] as $state): ?><option value="<?= e($state) ?>" <?= ($filters['estado']??'')===$state?'selected':'' ?>><?= e($state) ?></option><?php endforeach; ?></select></div><div class="col-md-6 col-xl-1 d-grid"><button class="btn btn-primary" type="submit" title="Aplicar filtros"><i class="fa-solid fa-filter"></i></button></div></form></div></div>
<div class="report-actions no-print"><button type="button" class="btn btn-success" data-report-excel><i class="fa-solid fa-file-excel me-2"></i>Excel</button><button type="button" class="btn btn-danger" data-report-pdf><i class="fa-solid fa-file-pdf me-2"></i>PDF</button><button type="button" class="btn btn-dark" onclick="window.print()"><i class="fa-solid fa-print me-2"></i>Imprimir</button></div>
<section class="report-export-root" data-report-export data-report-title="Reporte de Incidencias" data-file-name="Reporte_Incidencias_<?= e($filters['desde']) ?>_<?= e($filters['hasta']) ?>" data-logo-url="<?= e(asset('devioz-logo1.png')) ?>">
<div class="report-export-meta d-none"><span data-export-meta data-label="Periodo" data-value="<?= e(date('d/m/Y',strtotime($filters['desde'])).' al '.date('d/m/Y',strtotime($filters['hasta']))) ?>"></span><span data-export-meta data-label="Área" data-value="<?= e($selectedArea?:'Todas') ?>"></span><span data-export-meta data-label="Colaborador" data-value="<?= e($selectedCollaborator?:'Todos') ?>"></span><span data-export-meta data-label="Tipo" data-value="<?= e($selectedType?:'Todos') ?>"></span><span data-export-meta data-label="Estado" data-value="<?= e($stateLabel) ?>"></span><span data-export-meta data-label="Generado" data-value="<?= e($generatedAt->format('d/m/Y H:i')) ?>"></span></div>
<section class="print-report-header"><div class="print-brand-row"><img src="<?= e(asset('devioz-logo1.png')) ?>" alt="DEVIOZ" class="print-brand-logo"><div class="print-company">WORKFORCE360 AI</div><div class="print-report-title">REPORTE DE INCIDENCIAS</div></div><div class="print-report-meta"><div><strong>Periodo:</strong> <?= e(date('d/m/Y',strtotime($filters['desde']))) ?> al <?= e(date('d/m/Y',strtotime($filters['hasta']))) ?></div><div><strong>Tipo:</strong> <?= e($selectedType?:'Todos') ?></div><div><strong>Área:</strong> <?= e($selectedArea?:'Todas') ?></div><div><strong>Estado:</strong> <?= e($stateLabel) ?></div></div></section>
<div class="row g-3 mb-4 report-summary-grid" data-export-summary><div class="col-6 col-xl-3"><div class="report-summary-card"><span>Total incidencias</span><strong><?= e($summary['total']) ?></strong><small>Registros encontrados</small></div></div><div class="col-6 col-xl-3"><div class="report-summary-card"><span>Pendientes</span><strong><?= e($summary['pendientes']) ?></strong><small>Por revisar</small></div></div><div class="col-6 col-xl-3"><div class="report-summary-card"><span>Aprobadas</span><strong><?= e($summary['aprobadas']) ?></strong><small>Solicitudes validadas</small></div></div><div class="col-6 col-xl-3"><div class="report-summary-card"><span>Rechazadas</span><strong><?= e($summary['rechazadas']) ?></strong><small>Anuladas: <?= e($summary['anuladas']) ?></small></div></div></div>
<div class="card shadow-sm report-table-card"><div class="card-header py-3 px-4 no-print"><h2 class="h6 fw-bold mb-0"><i class="fa-solid fa-table-list me-2"></i>Detalle de incidencias</h2></div><div class="table-responsive"><table class="table app-table report-data-table align-middle mb-0" data-export-table><thead><tr><th>#</th><th>Código</th><th>Colaborador</th><th>Área</th><th>Tipo</th><th>Inicio</th><th>Fin</th><th>Estado</th><th>Motivo</th><th>Revisor</th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="10" class="text-center py-5 text-secondary">No se encontraron incidencias para los filtros seleccionados.</td></tr><?php else: foreach($rows as $i=>$row): ?><tr><td><?= e($i+1) ?></td><td><strong><?= e($row['codigo_trabajador']) ?></strong></td><td><div class="fw-semibold"><?= e($row['nombres'].' '.$row['apellidos']) ?></div><div class="small text-secondary"><?= e($row['cargo']?:'Sin cargo') ?></div></td><td><?= e($row['area_nombre']?:'—') ?></td><td><?= e($row['tipo_nombre']) ?></td><td><?= e(date('d/m/Y H:i',strtotime($row['fecha_inicio']))) ?></td><td><?= e($row['fecha_fin']?date('d/m/Y H:i',strtotime($row['fecha_fin'])):'—') ?></td><td><span class="badge <?= e($badgeForState((string)$row['estado'])) ?>"><?= e($row['estado']) ?></span></td><td><?= e($row['motivo']?:'—') ?></td><td><?= e($row['revisado_por_username']?:'—') ?></td></tr><?php endforeach; endif; ?></tbody></table></div></div><div class="print-report-footer">Workforce360 AI · DEVIOZ · Reporte generado automáticamente desde el sistema.</div></section>
<?php require BASE_PATH . '/app/Views/layouts/footer.php'; ?>
